// server.js

import express from 'express';
import numbro from 'numbro';
import dotenv from 'dotenv';
import path from 'path';
import { fileURLToPath } from 'url';

// Load environment variables from .env file
dotenv.config();
const SIM_API_KEY = process.env.SIM_API_KEY;

// Check if the API key is set
if (!SIM_API_KEY) {
    console.error("FATAL ERROR: SIM_API_KEY is not set in your environment variables.");
        process.exit(1); // Exit the process if no API key is found
        }

        // Set up __dirname for ES modules (needed to resolve file paths)
        const __filename = fileURLToPath(import.meta.url);
        const __dirname = path.dirname(__filename);

        // Initialize Express
        const app = express();

        // Configure Express settings
        app.set('view engine', 'ejs'); // Set EJS as the template engine
        app.set('views', path.join(__dirname, 'views')); // Set the directory for EJS templates
        app.use(express.static(path.join(__dirname, 'public'))); // Serve static files from the 'public' directory

        // Define the main route for the wallet page
        app.get('/', async (req, res) => {
            // Get wallet address and active tab from the URL query parameters
                const { 
                        walletAddress = '',
                                tab = 'tokens' // Default to 'tokens' tab if no tab is specified
                                    } = req.query;

                                        // Initialize variables to hold data
                                            let tokens = [];
                                                let totalWalletUSDValue = 0;
                                                    let activities = []; // Placeholder for future activity data
                                                        let collectibles = []; // Placeholder for future NFT data

                                                            // --- API LOGIC STARTS HERE ---
                                                                // Only fetch data if a wallet address is provided
                                                                    if (walletAddress) {
                                                                            try {
                                                                                        console.log(`Fetching balances for wallet: ${walletAddress}`);
                                                                                                    // Construct the API URL for the Balances API
                                                                                                                const apiUrl = `https://api.sim.xyz/v1/wallets/${walletAddress}/balances?chainId=1`; // chainId=1 for Ethereum Mainnet

                                                                                                                            // Make the API request using fetch
                                                                                                                                        const response = await fetch(apiUrl, {
                                                                                                                                                        method: 'GET',
                                                                                                                                                                        headers: {
                                                                                                                                                                                            'Authorization': `Bearer ${SIM_API_KEY}`,
                                                                                                                                                                                                                'Content-Type': 'application/json'
                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                            });

                                                                                                                                                                                                                                                        // Check if the request was successful
                                                                                                                                                                                                                                                                    if (!response.ok) {
                                                                                                                                                                                                                                                                                    // If the response is not OK, throw an error with the status text
                                                                                                                                                                                                                                                                                                    const errorBody = await response.text(); // Get more error details if available
                                                                                                                                                                                                                                                                                                                    throw new Error(`API request failed with status ${response.status}: ${response.statusText}. Details: ${errorBody}`);
                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                            const data = await response.json();
                                                                                                                                                                                                                                                                                                                                                        console.log("API Response received successfully.");

                                                                                                                                                                                                                                                                                                                                                                    // The API response structure might be { results: [...] } or just an array
                                                                                                                                                                                                                                                                                                                                                                                // We'll check for that and assign the tokens array accordingly
                                                                                                                                                                                                                                                                                                                                                                                            tokens = data.results || data || [];

                                                                                                                                                                                                                                                                                                                                                                                                        // Calculate the total USD value of the wallet
                                                                                                                                                                                                                                                                                                                                                                                                                    let totalValue = 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                tokens.forEach(token => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                // Ensure value_usd is a number before adding
                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (typeof token.value_usd === 'number') {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    totalValue += token.value_usd;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            totalWalletUSDValue = numbro(totalValue).formatCurrency('$0,0.00');

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Format the token amounts and USD values for better display
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    tokens = tokens.map(token => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Format amount to a readable number, avoiding scientific notation for very small numbers
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const amount = parseFloat(token.amount);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    let amountFormatted;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (isNaN(amount)) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        amountFormatted = 'N/A';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        } else if (amount < 0.0001 && amount > 0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            amountFormatted = '< 0.0001'; // For very small amounts
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                amountFormatted = numbro(amount).format('0,0.0000');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ...token,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        amountFormatted: amountFormatted,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            valueUSDFormatted: numbro(token.value_usd).formatCurrency('$0,0.00')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            console.error("Failed to fetch wallet data:", error.message);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // In case of an error, we'll keep tokens empty and show an error message on the frontend
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // We can pass the error to the template to display it
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                totalWalletUSDValue = 'Error';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // --- API LOGIC ENDS HERE ---

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Render the 'wallet.ejs' template and pass the data to it
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        res.render('wallet', {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                walletAddress: walletAddress,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        currentTab: tab,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                totalWalletUSDValue: totalWalletUSDValue,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        tokens: tokens,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                activities: activities,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        collectibles: collectibles
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Start the server on port 3001
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            app.listen(3001, () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                console.log(`Server running at http://localhost:3001`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                