// src/services/keyManager.js
import CryptoJS from 'crypto-js';
import * as bip39 from 'bip39';
import HDKey from 'hdkey';

class KeyManager {
  constructor() {
      this.encryptionKey = null;
        }

          // 🔐 Mnemonic phrase generate کریں (12 words)
            generateMnemonic() {
                try {
                      const mnemonic = bip39.generateMnemonic();
                            console.log('✅ Mnemonic generated successfully - keyManager.js:15');
                                  return mnemonic;
                                      } catch (error) {
                                            console.error('❌ Error generating mnemonic: - keyManager.js:18', error);
                                                  throw new Error('Failed to generate mnemonic');
                                                      }
                                                        }

                                                          // 🔑 Mnemonic سے wallet بنائیں
                                                            createWalletFromMnemonic(mnemonic, password) {
                                                                try {
                                                                      // Validate mnemonic
                                                                            if (!bip39.validateMnemonic(mnemonic)) {
                                                                                    throw new Error('Invalid mnemonic phrase');
                                                                                          }

                                                                                                // Generate seed from mnemonic
                                                                                                      const seed = bip39.mnemonicToSeedSync(mnemonic);
                                                                                                            
                                                                                                                  // Create HD wallet
                                                                                                                        const hdkey = HDKey.fromMasterSeed(seed);
                                                                                                                              
                                                                                                                                    // Derive first account (m/44'/60'/0'/0/0 - Ethereum path)
                                                                                                                                          const wallet = hdkey.derive("m/44'/60'/0'/0/0");
                                                                                                                                                
                                                                                                                                                      const walletData = {
                                                                                                                                                              address: `0x${wallet.publicKey.toString('hex')}`,
                                                                                                                                                                      privateKey: wallet.privateKey.toString('hex'),
                                                                                                                                                                              publicKey: wallet.publicKey.toString('hex'),
                                                                                                                                                                                      mnemonic: mnemonic
                                                                                                                                                                                            };

                                                                                                                                                                                                  // Encrypt private data
                                                                                                                                                                                                        const encryptedData = this.encryptWalletData(walletData, password);
                                                                                                                                                                                                              
                                                                                                                                                                                                                    console.log('✅ Wallet created successfully - keyManager.js:50');
                                                                                                                                                                                                                          return {
                                                                                                                                                                                                                                  address: walletData.address,
                                                                                                                                                                                                                                          encrypted: encryptedData
                                                                                                                                                                                                                                                };
                                                                                                                                                                                                                                                    } catch (error) {
                                                                                                                                                                                                                                                          console.error('❌ Error creating wallet: - keyManager.js:56', error);
                                                                                                                                                                                                                                                                throw error;
                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                        // 🔒 Wallet data encrypt کریں
                                                                                                                                                                                                                                                                          encryptWalletData(walletData, password) {
                                                                                                                                                                                                                                                                              try {
                                                                                                                                                                                                                                                                                    const dataString = JSON.stringify(walletData);
                                                                                                                                                                                                                                                                                          const encrypted = CryptoJS.AES.encrypt(dataString, password).toString();
                                                                                                                                                                                                                                                                                                return encrypted;
                                                                                                                                                                                                                                                                                                    } catch (error) {
                                                                                                                                                                                                                                                                                                          console.error('❌ Encryption error: - keyManager.js:68', error);
                                                                                                                                                                                                                                                                                                                throw new Error('Failed to encrypt wallet data');
                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                        // 🔓 Wallet data decrypt کریں
                                                                                                                                                                                                                                                                                                                          decryptWalletData(encryptedData, password) {
                                                                                                                                                                                                                                                                                                                              try {
                                                                                                                                                                                                                                                                                                                                    const decrypted = CryptoJS.AES.decrypt(encryptedData, password);
                                                                                                                                                                                                                                                                                                                                          const decryptedString = decrypted.toString(CryptoJS.enc.Utf8);
                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                      if (!decryptedString) {
                                                                                                                                                                                                                                                                                                                                                              throw new Error('Invalid password or corrupted data');
                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                return JSON.parse(decryptedString);
                                                                                                                                                                                                                                                                                                                                                                                    } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                          console.error('❌ Decryption error: - keyManager.js:85', error);
                                                                                                                                                                                                                                                                                                                                                                                                throw new Error('Failed to decrypt wallet data');
                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                        // 💾 Wallet کو local storage میں محفوظ کریں
                                                                                                                                                                                                                                                                                                                                                                                                          saveWallet(walletData, walletName = 'default') {
                                                                                                                                                                                                                                                                                                                                                                                                              try {
                                                                                                                                                                                                                                                                                                                                                                                                                    const walletKey = `wallet_${walletName}`;
                                                                                                                                                                                                                                                                                                                                                                                                                          localStorage.setItem(walletKey, JSON.stringify(walletData));
                                                                                                                                                                                                                                                                                                                                                                                                                                console.log('✅ Wallet saved to localStorage - keyManager.js:95');
                                                                                                                                                                                                                                                                                                                                                                                                                                      return true;
                                                                                                                                                                                                                                                                                                                                                                                                                                          } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                console.error('❌ Error saving wallet: - keyManager.js:98', error);
                                                                                                                                                                                                                                                                                                                                                                                                                                                      return false;
                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                              // 📂 محفوظ شدہ wallet لوڈ کریں
                                                                                                                                                                                                                                                                                                                                                                                                                                                                loadWallet(walletName = 'default') {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const walletKey = `wallet_${walletName}`;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const walletData = localStorage.getItem(walletKey);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (!walletData) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return null;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      return JSON.parse(walletData);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                console.error('❌ Error loading wallet: - keyManager.js:115', error);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      return null;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            export default KeyManager;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            